# Generated by Django 2.2b1 on 2019-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('contact_info', models.CharField(max_length=250)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('open_days', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=1000)),
                ('info', models.TextField(max_length=20000)),
            ],
        ),
    ]
