# Generated by Django 2.2b1 on 2019-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0002_auto_20190317_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/campuses'),
        ),
    ]
