# Generated by Django 2.2b1 on 2019-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('steps', models.TextField(max_length=2500)),
                ('image', models.CharField(max_length=1000)),
                ('additional_info', models.TextField(max_length=10000)),
            ],
        ),
    ]
