# Generated by Django 2.2b1 on 2019-03-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscontent',
            name='news',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsContent',
        ),
    ]
