# Generated by Django 2.2b1 on 2019-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20190311_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=10000)),
                ('author', models.CharField(max_length=250)),
            ],
        ),
    ]
