# Generated by Django 2.2b1 on 2019-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_auto_20190311_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
