# Generated by Django 2.2b1 on 2019-03-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
