# Generated by Django 2.2b1 on 2019-03-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homePage', '0006_auto_20190311_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=10000)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=1000)),
                ('home_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.HomeContent')),
            ],
        ),
    ]
