# Generated by Django 2.2b1 on 2019-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_content_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/homePage'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='images/homePage/thumbnail'),
        ),
    ]
