# Generated by Django 2.2b1 on 2019-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='middle_name',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
