# Generated by Django 2.2b1 on 2019-03-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0003_auto_20190317_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='school',
            field=models.CharField(choices=[('BFA', 'BFA - Bachelor in Fine Arts'), ('BMMA', 'BMMA - Bachelor in Multimedia Arts'), ('BSIS', 'Bachelor of Science in Information System')], default='K12 Grad', max_length=1),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='program',
            field=models.CharField(choices=[('BFA', 'BFA - Bachelor in Fine Arts'), ('BMMA', 'BMMA - Bachelor in Multimedia Arts'), ('BSIS', 'Bachelor of Science in Information System')], default='BFA', max_length=1),
        ),
    ]
