# Generated by Django 2.2b1 on 2019-03-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0004_auto_20190317_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='program',
            new_name='interested_course',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='school',
            new_name='previous_schooling',
        ),
    ]
