# Generated by Django 2.2b1 on 2019-03-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0005_auto_20190317_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='company',
        ),
    ]
