# Generated by Django 2.2b1 on 2019-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0006_remove_contactinfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='previous_schooling',
            field=models.CharField(choices=[('K12 Grad', 'K12 Graduate'), ('College Trans', 'College Transferee'), ('College Grad', 'College Graduate')], default='K12 Grad', max_length=1),
        ),
    ]
