# Generated by Django 2.2b1 on 2019-03-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0007_auto_20190317_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='interested_course',
            field=models.CharField(choices=[('BFA', 'BFA - Bachelor in Fine Arts'), ('BMMA', 'BMMA - Bachelor in Multimedia Arts'), ('BSIS', 'Bachelor of Science in Information System')], default='BFA', max_length=4),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='previous_schooling',
            field=models.CharField(choices=[('K12 Grad', 'K12 Graduate'), ('College Trans', 'College Transferee'), ('College Grad', 'College Graduate')], default='K12 Grad', max_length=13),
        ),
    ]
