# Generated by Django 2.2b1 on 2019-03-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0008_auto_20190317_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='birthday',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='middle_name',
            field=models.CharField(max_length=250),
        ),
    ]
