# Generated by Django 2.2b1 on 2019-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/about'),
        ),
    ]
