# Generated by Django 2.2b1 on 2019-03-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_program_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
