# Generated by Django 2.2b1 on 2019-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcontent',
            name='program_image',
            field=models.ImageField(blank=True, upload_to='images/programs/content'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_image',
            field=models.ImageField(blank=True, upload_to='images/programs'),
        ),
    ]
