# Generated by Django 2.2b1 on 2019-03-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20190324_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programcontent',
            old_name='program_image',
            new_name='content_image',
        ),
    ]
